"use client";

import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ToasterContext from './context/ToasterContext';
import AuthContext from './context/AuthContext';
import { ConfettiProvider } from '@/components/provider/confetti-provider';
import { Toaster } from '@/components/ui/toaster';
import { Navbar } from '@/components/navigation-bar/Navbar';

import { Button } from '@/components/ui/button';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Learner',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <AuthContext>
                    <ConfettiProvider />
                    <ToasterContext />
                    <Toaster />
                    <Navbar />
                    {children}
                </AuthContext>
            </body>
        </html>
    );
}
